/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SeenBody
    /// </summary>
    [DataContract]
        public partial class SeenBody :  IEquatable<SeenBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeenBody" /> class.
        /// </summary>
        /// <param name="whatsappID">Идентификатор Whatsapp ID.</param>
        /// <param name="recipient">recipient.</param>
        public SeenBody(string whatsappID = default(string), AnyOfseenBodyRecipient recipient = default(AnyOfseenBodyRecipient))
        {
            this.WhatsappID = whatsappID;
            this.Recipient = recipient;
        }
        
        /// <summary>
        /// Идентификатор Whatsapp ID
        /// </summary>
        /// <value>Идентификатор Whatsapp ID</value>
        [DataMember(Name="WhatsappID", EmitDefaultValue=false)]
        public string WhatsappID { get; set; }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [DataMember(Name="recipient", EmitDefaultValue=false)]
        public AnyOfseenBodyRecipient Recipient { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SeenBody {\n");
            sb.Append("  WhatsappID: ").Append(WhatsappID).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SeenBody);
        }

        /// <summary>
        /// Returns true if SeenBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SeenBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SeenBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WhatsappID == input.WhatsappID ||
                    (this.WhatsappID != null &&
                    this.WhatsappID.Equals(input.WhatsappID))
                ) && 
                (
                    this.Recipient == input.Recipient ||
                    (this.Recipient != null &&
                    this.Recipient.Equals(input.Recipient))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WhatsappID != null)
                    hashCode = hashCode * 59 + this.WhatsappID.GetHashCode();
                if (this.Recipient != null)
                    hashCode = hashCode * 59 + this.Recipient.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
