/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnyOfsendBodyMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnyOfsendBodyMessageTests
    {
        // TODO uncomment below to declare an instance variable for AnyOfsendBodyMessage
        //private AnyOfsendBodyMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnyOfsendBodyMessage
            //instance = new AnyOfsendBodyMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnyOfsendBodyMessage
        /// </summary>
        [Test]
        public void AnyOfsendBodyMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnyOfsendBodyMessage
            //Assert.IsInstanceOfType<AnyOfsendBodyMessage> (instance, "variable 'instance' is a AnyOfsendBodyMessage");
        }



    }

}
