/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnyOfsendBodyRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnyOfsendBodyRecipientTests
    {
        // TODO uncomment below to declare an instance variable for AnyOfsendBodyRecipient
        //private AnyOfsendBodyRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnyOfsendBodyRecipient
            //instance = new AnyOfsendBodyRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnyOfsendBodyRecipient
        /// </summary>
        [Test]
        public void AnyOfsendBodyRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnyOfsendBodyRecipient
            //Assert.IsInstanceOfType<AnyOfsendBodyRecipient> (instance, "variable 'instance' is a AnyOfsendBodyRecipient");
        }



    }

}
