/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseChat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseChatTests
    {
        // TODO uncomment below to declare an instance variable for ResponseChat
        //private ResponseChat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseChat
            //instance = new ResponseChat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseChat
        /// </summary>
        [Test]
        public void ResponseChatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseChat
            //Assert.IsInstanceOfType<ResponseChat> (instance, "variable 'instance' is a ResponseChat");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsGroup'
        /// </summary>
        [Test]
        public void IsGroupTest()
        {
            // TODO unit test for the property 'IsGroup'
        }
        /// <summary>
        /// Test the property 'IsReadOnly'
        /// </summary>
        [Test]
        public void IsReadOnlyTest()
        {
            // TODO unit test for the property 'IsReadOnly'
        }
        /// <summary>
        /// Test the property 'UnreadCount'
        /// </summary>
        [Test]
        public void UnreadCountTest()
        {
            // TODO unit test for the property 'UnreadCount'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Pinned'
        /// </summary>
        [Test]
        public void PinnedTest()
        {
            // TODO unit test for the property 'Pinned'
        }
        /// <summary>
        /// Test the property 'IsMuted'
        /// </summary>
        [Test]
        public void IsMutedTest()
        {
            // TODO unit test for the property 'IsMuted'
        }
        /// <summary>
        /// Test the property 'MuteExpiration'
        /// </summary>
        [Test]
        public void MuteExpirationTest()
        {
            // TODO unit test for the property 'MuteExpiration'
        }
        /// <summary>
        /// Test the property 'GroupMetadata'
        /// </summary>
        [Test]
        public void GroupMetadataTest()
        {
            // TODO unit test for the property 'GroupMetadata'
        }

    }

}
