/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseChatGroupMetadataParticipants
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseChatGroupMetadataParticipantsTests
    {
        // TODO uncomment below to declare an instance variable for ResponseChatGroupMetadataParticipants
        //private ResponseChatGroupMetadataParticipants instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseChatGroupMetadataParticipants
            //instance = new ResponseChatGroupMetadataParticipants();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseChatGroupMetadataParticipants
        /// </summary>
        [Test]
        public void ResponseChatGroupMetadataParticipantsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseChatGroupMetadataParticipants
            //Assert.IsInstanceOfType<ResponseChatGroupMetadataParticipants> (instance, "variable 'instance' is a ResponseChatGroupMetadataParticipants");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsAdmin'
        /// </summary>
        [Test]
        public void IsAdminTest()
        {
            // TODO unit test for the property 'IsAdmin'
        }
        /// <summary>
        /// Test the property 'IsSuperAdmin'
        /// </summary>
        [Test]
        public void IsSuperAdminTest()
        {
            // TODO unit test for the property 'IsSuperAdmin'
        }

    }

}
