/* 
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SendBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SendBodyTests
    {
        // TODO uncomment below to declare an instance variable for SendBody
        //private SendBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendBody
            //instance = new SendBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendBody
        /// </summary>
        [Test]
        public void SendBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SendBody
            //Assert.IsInstanceOfType<SendBody> (instance, "variable 'instance' is a SendBody");
        }


        /// <summary>
        /// Test the property 'WhatsappID'
        /// </summary>
        [Test]
        public void WhatsappIDTest()
        {
            // TODO unit test for the property 'WhatsappID'
        }
        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Test]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Test]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
